Django 2.x url import error
Fixed "ImportError: cannot import name 'url' from 'django.conf.urls'" error which was occurring when using  with Django 2.x